configfile: "config.yaml"
import os

def get_param_year(wildcards):
    return float(config["event"][wildcards.event])

def get_sample_directory(wildcards):
    return "data/" + wildcards.event

def get_output_directory(wildcards):
    return config["dataset"][wildcards.dataset]

rule all:
    input:
        expand("plot/posterior/{event}.jpg", event=config["event"]),
        # expand("plot/datasets/{dataset}.jpg", dataset=config["dataset"]),
        expand("diagnostics/{event}_{cbm_model}.jpg", event=config["event"], cbm_model=config["cbm_model"]),
        expand("diagnostics/{event}.jpg", event=config["event"]),

rule sample:
    input:
        get_sample_directory
    output:
        "chain/{event}_{cbm_model}.npy"
    params:
        year = get_param_year,
        cbm_model = "{cbm_model}"
    script:
        "scripts/sample.py"

rule plot_posterior:
    input:
        expand("chain/{event}_{cbm_model}.npy", event="{event}", cbm_model=config["cbm_model"])
    output:
        "plot/posterior/{event}.jpg"
    params:
        cbm_model = expand("{cbm_model}", cbm_model=config["cbm_model"]),
        event = "{event}"
    script:
        "scripts/plot_one.py"

# rule plot_diagnostics:
#     input:
#         "chain/{event}_{cbm_model}.npy"
#     output:
#         "diagnostics/{event}_{cbm_model}.jpg"
#     params:
#         event = "{event}",
#         cbm_model = "{cbm_model}"
#     script:
#         "scripts/chain_diagnostics.py"

rule get_event_average:
    input:
        "data/{event}"
    output:
        "data/mean/{event}.csv"
    params:
        event = "{event}"
    script:
        "scripts/event_average.py"

rule plot_continuous_d14c:
    input:
        "data/mean/{event}.csv"
    output:
        "diagnostics/{event}.jpg"
    params:
        event = "{event}",
        cbm_model = expand("{cbm_model}", cbm_model=config["cbm_model"]),
    script:
        "scripts/continuous_d14c.py"

rule plot_dataset:
    input:
        get_output_directory
    output:
        "plot/datasets/{dataset}.jpg"
    script:
        "scripts/plot_dataset.py"

# rule plot_all:
#     input:
#         expand("chain/{event}_{cbm_model}.npy", event=config["event"], cbm_model=config["cbm_model"])
