configfile: "config.yaml"
def get_path(wildcards):
    return config["samples"][wildcards.sample]

rule all:
    input:
        expand("plot/{sample}.png", sample=config["samples"])

rule plot:
    input:
        get_path
    output:
        "plot/{sample}.png"
    script:
        "scripts/plot.py"
